Fix referenced before assignment error in execute
prestosql/presto-python-client pull request #49
Opened 2020-10-14 22:43 UTC by rushton

Fixes a runtime error with added_prepare_header variable not being
present when an exception happens during creation of a prepared
statement.

2020-10-14 23:40 UTC, harph commented
@rushton Thanks for fixing this. Do you mind adding a test for this?

2020-10-15 00:13 UTC, rushton commented
test added for this case

2020-10-15 07:30 UTC, findepi approved these changes

2020-10-15 07:30 UTC, findepi commented
Thanks @rushton!

2020-10-15 07:37 UTC, hashhar requested changes

2020-10-15 07:38 UTC, hashhar commented
Thanks @rushton for fixing this.

2020-10-15 07:38 UTC, findepi commented on presto/dbapi.py
> +            added_prepare_header = self._prepare_statement(
my understaanding is that the finally block is about cleaning up the prepare. so if prepare fails, there is no cleanup due
can you please double check me on this?

2020-10-15 07:45 UTC, hashhar approved these changes
LGTM

2020-10-15 07:55 UTC, merged

2020-10-15 07:55 UTC, findepi commented
Merged, thanks!